version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./app/model.pth:/code/model.pth
      - ./utils:/code/utils
      - ./big_model:/code/big_model
      - ./data/inference_cache.pkl:/code/data/inference_cache.pkl
      - ./models/20250612_234603/best_model_3.pth:/code/models/20250612_234603/best_model_3.pth
    # The 'networks' block allows containers to communicate with each other
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app.py:/code/streamlit_app.py
      - ./utils:/code/utils
    # This service depends on the backend starting first
    depends_on:
      - backend
    networks:
      - app-network
    # We must update the environment variable to point to the backend service name
    environment:
      - FASTAPI_URL=http://backend:8000

networks:
  app-network:
    driver: bridge

