version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./utils:/code/utils
      - ./big_model:/code/big_model
      - ./data:/code/data
      - ./skipgram_models:/code/skipgram_models
    environment:
      - PYTHONPATH=/code
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app.py:/code/streamlit_app.py
      - ./utils:/code/utils
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - FASTAPI_URL=http://backend:8000
      - PYTHONPATH=/code

networks:
  app-network:
    driver: bridge

